import { WeaponDef, WeaponId } from '../types';

export const WEAPON_REGISTRY: Record<WeaponId, WeaponDef> = {
  famas: {
    id: 'famas',
    name: 'FAMAS F1',
    persianName: 'فاماس (FAMAS)',
    slot: 1,
    category: 'rifle',
    price: 2050,
    damageBody: 30,
    damageHead: 120,
    damageArmLeg: 22,
    clipSize: 25,
    maxReserveAmmo: 90,
    fireRateMs: 90, // Fast 666 RPM full auto, 800 RPM in burst
    reloadTimeMs: 2300,
    recoilSpread: 0.022,
    recoilKickback: 0.032,
    range: 160,
    availableFireModes: ['auto', 'burst'],
    defaultFireMode: 'auto',
    burstCount: 3,
    burstDelayMs: 65,
    description: 'تفنگ هجومی بولپاپ ارتش فرانسه. دارای حالت رگبار اتوماتیک و شلیک ۳ تیر رگباری (۳-Round Burst) بسیار دقیق.',
    iconName: 'crosshair',
    killReward: 300,
    teamAccess: 'CT'
  },
  ak47: {
    id: 'ak47',
    name: 'AK-47 Kalashnikov',
    persianName: 'کلاشینکف AK-47',
    slot: 1,
    category: 'rifle',
    price: 2700,
    damageBody: 36,
    damageHead: 140, // 1-shot headshot even with helmet
    damageArmLeg: 27,
    clipSize: 30,
    maxReserveAmmo: 90,
    fireRateMs: 100,
    reloadTimeMs: 2400,
    recoilSpread: 0.035,
    recoilKickback: 0.045,
    range: 180,
    availableFireModes: ['auto'],
    defaultFireMode: 'auto',
    description: 'تفنگ افسانه‌ای تروریست‌ها با قدرت تخریب بالا و قابلیت هدشات تک‌تیر مرگبار حتی با کلاهخود.',
    iconName: 'gun',
    killReward: 300,
    teamAccess: 'T'
  },
  m4a1: {
    id: 'm4a1',
    name: 'M4A1-S Carbine',
    persianName: 'ام۴ صداخفه‌کن‌دار M4A1',
    slot: 1,
    category: 'rifle',
    price: 2900,
    damageBody: 33,
    damageHead: 130,
    damageArmLeg: 25,
    clipSize: 25,
    maxReserveAmmo: 75,
    fireRateMs: 100,
    reloadTimeMs: 2200,
    recoilSpread: 0.018,
    recoilKickback: 0.025,
    range: 180,
    availableFireModes: ['auto'],
    defaultFireMode: 'auto',
    canHaveSilencer: true,
    description: 'تفنگ سازمانی ضدتروریست‌ها با صداخفه‌کن، لگد بسیار کم و دقت شگفت‌انگیز در فواصل دور.',
    iconName: 'crosshair',
    killReward: 300,
    teamAccess: 'CT'
  },
  awp: {
    id: 'awp',
    name: 'AWP Magnum Sniper',
    persianName: 'تک‌تیرانداز ای‌دبلیوپی (AWP)',
    slot: 1,
    category: 'sniper',
    price: 4750,
    damageBody: 115, // 1-shot body kill
    damageHead: 400,
    damageArmLeg: 85,
    clipSize: 10,
    maxReserveAmmo: 30,
    fireRateMs: 1300, // Bolt action cycle
    reloadTimeMs: 3400,
    recoilSpread: 0.08,
    recoilKickback: 0.12,
    range: 300,
    availableFireModes: ['bolt'],
    defaultFireMode: 'bolt',
    hasScope: true,
    scopeLevels: [25, 10], // 4x and 8x zoom
    description: 'سنگین‌ترین اسلحه بازی با زوم دو مرحله‌ای و مرگ در اثر یک شلیک به سینه یا سر.',
    iconName: 'target',
    killReward: 100,
    teamAccess: 'all'
  },
  scout: {
    id: 'scout',
    name: 'SSG 08 Scout',
    persianName: 'اسکات سبک SSG 08',
    slot: 1,
    category: 'sniper',
    price: 1700,
    damageBody: 75,
    damageHead: 300,
    damageArmLeg: 55,
    clipSize: 10,
    maxReserveAmmo: 40,
    fireRateMs: 1000,
    reloadTimeMs: 2800,
    recoilSpread: 0.04,
    recoilKickback: 0.06,
    range: 250,
    availableFireModes: ['bolt'],
    defaultFireMode: 'bolt',
    hasScope: true,
    scopeLevels: [30, 15],
    description: 'تک‌تیرانداز ارزان و بسیار سبک با سرعت دویدن بالا و هدشات قطعی ۱۰۰٪.',
    iconName: 'crosshair',
    killReward: 300,
    teamAccess: 'all'
  },
  negev: {
    id: 'negev',
    name: 'Negev LMG',
    persianName: 'تیربار سنگین نگِو (Negev)',
    slot: 1,
    category: 'heavy',
    price: 5000,
    damageBody: 36,
    damageHead: 145,
    damageArmLeg: 26,
    clipSize: 150,
    maxReserveAmmo: 300,
    fireRateMs: 75, // 800 RPM continuous barrage
    reloadTimeMs: 4200,
    recoilSpread: 0.015, // settles into tight laser beam spray
    recoilKickback: 0.022,
    range: 170,
    availableFireModes: ['auto'],
    defaultFireMode: 'auto',
    description: 'تیربار سنگین رگباری پیشرفته با جعبه خشاب ۱۵۰ تیری! با حجم آتش ویرانگر، لگد صفر پس از شلیک اولیه و قدرت مانور بالا در کنترل مناطق حساس نقشه.',
    iconName: 'zap',
    killReward: 300,
    teamAccess: 'all'
  },
  m249: {
    id: 'm249',
    name: 'M249 Para SAW',
    persianName: 'تیربار ام۲۴۹ پارا (M249)',
    slot: 1,
    category: 'heavy',
    price: 1700,
    damageBody: 38,
    damageHead: 150,
    damageArmLeg: 28,
    clipSize: 100,
    maxReserveAmmo: 200,
    fireRateMs: 80, // 750 RPM
    reloadTimeMs: 4400,
    recoilSpread: 0.038,
    recoilKickback: 0.048,
    range: 180,
    availableFireModes: ['auto'],
    defaultFireMode: 'auto',
    description: 'تیربار قدرتمند سازمانی با نوار فشنگ ۱۰۰ تیری و قدرت نفوذ سهمگین در جلیقه ضدگلوله با قیمت اقتصادی ۱۷۰۰ دلار، مناسب برای راش‌های هجومی با حجم آتش بالا.',
    iconName: 'zap',
    killReward: 300,
    teamAccess: 'all'
  },
  xm1014: {
    id: 'xm1014',
    name: 'XM1014 Auto Shotgun',
    persianName: 'شات‌گان رگباری اتوماتیک XM1014',
    slot: 1,
    category: 'shotgun',
    price: 2000,
    damageBody: 20, // per pellet (6 pellets = 120 total body)
    damageHead: 80, // per pellet headshot
    damageArmLeg: 15,
    pelletsCount: 6,
    clipSize: 7,
    maxReserveAmmo: 32,
    fireRateMs: 240, // Semi-auto rapid spam
    reloadTimeMs: 2500,
    recoilSpread: 0.075,
    recoilKickback: 0.065,
    range: 45,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'شات‌گان نیمه‌اتوماتیک با نواخت تیر سریع و شلیک همزمان ۶ ساچمه مرگبار در هر شلیک؛ انفجار ساچمه‌ای مرگ‌آور در فواصل نزدیک و راهروهای باریک.',
    iconName: 'target',
    killReward: 900,
    teamAccess: 'all'
  },
  nova: {
    id: 'nova',
    name: 'Nova Pump Shotgun',
    persianName: 'شات‌گان پمپی نوا (Nova)',
    slot: 1,
    category: 'shotgun',
    price: 1050,
    damageBody: 26, // 8 pellets = 208 total
    damageHead: 95,
    damageArmLeg: 18,
    pelletsCount: 8,
    clipSize: 8,
    maxReserveAmmo: 32,
    fireRateMs: 800, // Pump action
    reloadTimeMs: 2800,
    recoilSpread: 0.052,
    recoilKickback: 0.08,
    range: 55,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'شات‌گان پمپی مقرون‌به‌صرفه با الگوی ساچمه‌های فوق‌العاده متمرکز و برد بالاتر نسبت به سایر شات‌گان‌ها، با جایزه ۳ برابر پول ($900) به ازای هر کیل.',
    iconName: 'target',
    killReward: 900,
    teamAccess: 'all'
  },
  mag7: {
    id: 'mag7',
    name: 'MAG-7 Tactical',
    persianName: 'شات‌گان تاکتیکال مَگ-۷ (MAG-7)',
    slot: 1,
    category: 'shotgun',
    price: 1300,
    damageBody: 30, // 8 pellets = 240 total
    damageHead: 110,
    damageArmLeg: 20,
    pelletsCount: 8,
    clipSize: 5,
    maxReserveAmmo: 30,
    fireRateMs: 650,
    reloadTimeMs: 2100, // Fast box magazine reload
    recoilSpread: 0.062,
    recoilKickback: 0.075,
    range: 48,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'شات‌گان تاکتیکال جمع‌وجور با خشاب جعبه‌ای تعویض سریع و قدرت توقف وحشتناک در درگیری‌های مستقیم گوشه‌ها و سایت‌ها.',
    iconName: 'target',
    killReward: 900,
    teamAccess: 'all'
  },
  sawedoff: {
    id: 'sawedoff',
    name: 'Sawed-Off Shotgun',
    persianName: 'شات‌گان لوله‌کوتاه دوعنصری (Sawed-Off)',
    slot: 1,
    category: 'shotgun',
    price: 1100,
    damageBody: 32, // 8 pellets = 256 total
    damageHead: 115,
    damageArmLeg: 22,
    pelletsCount: 8,
    clipSize: 7,
    maxReserveAmmo: 28,
    fireRateMs: 780,
    reloadTimeMs: 2900,
    recoilSpread: 0.09,
    recoilKickback: 0.09,
    range: 35,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'شات‌گان لوله‌کوتاه سنتی با پخش ساچمه‌ای فوق‌العاده عریض و مهلک؛ قادر به نابودی همزمان چند دشمن در اتاق‌های کوچک.',
    iconName: 'target',
    killReward: 900,
    teamAccess: 'all'
  },
  spas12: {
    id: 'spas12',
    name: 'SPAS-12 Combat Shotgun',
    persianName: 'شات‌گان رزمی اسپاس-۱۲ (SPAS-12)',
    slot: 1,
    category: 'shotgun',
    price: 1750,
    damageBody: 28, // 8 pellets = 224 total
    damageHead: 105,
    damageArmLeg: 20,
    pelletsCount: 8,
    clipSize: 8,
    maxReserveAmmo: 32,
    fireRateMs: 420,
    reloadTimeMs: 2600,
    recoilSpread: 0.068,
    recoilKickback: 0.082,
    range: 50,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'شات‌گان رزمی افسانه‌ای با قنداق تاشو فلزی، لوله ضدحرارت و شلیک نیمه‌اتوماتیک کوبنده با تخریب بالا در راش‌های تهاجمی.',
    iconName: 'target',
    killReward: 900,
    teamAccess: 'all'
  },
  bizon: {
    id: 'bizon',
    name: 'PP-19 Bizon',
    persianName: 'مسلسل رگباری بیزون (PP-Bizon)',
    slot: 1,
    category: 'smg',
    price: 1400,
    damageBody: 27,
    damageHead: 95,
    damageArmLeg: 21,
    clipSize: 64,
    maxReserveAmmo: 128,
    fireRateMs: 80, // 750 RPM
    reloadTimeMs: 2400,
    recoilSpread: 0.026,
    recoilKickback: 0.022,
    range: 125,
    availableFireModes: ['auto'],
    defaultFireMode: 'auto',
    description: 'مسلسل سبک با خشاب استوانه‌ای مارپیچ ۶۴ تیری؛ ایده‌آل برای رگبار بستن مداوم حین دویدن و راش‌های سریع بدون وقفه.',
    iconName: 'zap',
    killReward: 600,
    teamAccess: 'all'
  },
  p90: {
    id: 'p90',
    name: 'FN P90',
    persianName: 'پی‌نود P90',
    slot: 1,
    category: 'smg',
    price: 2350,
    damageBody: 26,
    damageHead: 90,
    damageArmLeg: 20,
    clipSize: 50,
    maxReserveAmmo: 100,
    fireRateMs: 70, // 857 RPM
    reloadTimeMs: 2700,
    recoilSpread: 0.038,
    recoilKickback: 0.024,
    range: 120,
    availableFireModes: ['auto'],
    defaultFireMode: 'auto',
    description: 'مسلسل سبک با خشاب ۵۰ تیری عظیم، مناسب راش دادن و تیراندازی هنگام حرکت سریع.',
    iconName: 'zap',
    killReward: 300,
    teamAccess: 'all'
  },
  mp5sd: {
    id: 'mp5sd',
    name: 'MP5-SD Silenced',
    persianName: 'ام‌پی‌فایو MP5-SD',
    slot: 1,
    category: 'smg',
    price: 1500,
    damageBody: 27,
    damageHead: 100,
    damageArmLeg: 21,
    clipSize: 30,
    maxReserveAmmo: 120,
    fireRateMs: 80,
    reloadTimeMs: 2300,
    recoilSpread: 0.022,
    recoilKickback: 0.020,
    range: 130,
    availableFireModes: ['auto'],
    defaultFireMode: 'auto',
    canHaveSilencer: true,
    description: 'مسلسل سبک بی‌صدا با صداخفه‌کن داخلی، لگد ناچیز و سرعت حرکت فوق‌العاده.',
    iconName: 'shield',
    killReward: 600,
    teamAccess: 'all'
  },
  deagle: {
    id: 'deagle',
    name: 'Desert Eagle .50',
    persianName: 'دزرت ایگل ۵۰ کالیبر',
    slot: 2,
    category: 'pistol',
    price: 700,
    damageBody: 53,
    damageHead: 200,
    damageArmLeg: 40,
    clipSize: 7,
    maxReserveAmmo: 35,
    fireRateMs: 250,
    reloadTimeMs: 1900,
    recoilSpread: 0.045,
    recoilKickback: 0.065,
    range: 140,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'کلت سنگین کالیبر ۵۰، نیازمند مهارت بالا اما با دمیج سهمگین و هدشات در فاصله نزدیک.',
    iconName: 'award',
    killReward: 300,
    teamAccess: 'all'
  },
  glock: {
    id: 'glock',
    name: 'Glock-18',
    persianName: 'گلاک ۱۸ (Glock-18)',
    slot: 2,
    category: 'pistol',
    price: 200,
    damageBody: 28,
    damageHead: 90,
    damageArmLeg: 20,
    clipSize: 20,
    maxReserveAmmo: 120,
    fireRateMs: 150,
    reloadTimeMs: 1800,
    recoilSpread: 0.025,
    recoilKickback: 0.025,
    range: 110,
    availableFireModes: ['semi', 'burst'],
    defaultFireMode: 'semi',
    burstCount: 3,
    burstDelayMs: 60,
    description: 'کلت سازمانی تروریست‌ها با خشاب ۲۰ تیری و قابلیت سوئیچ بین حالت تک‌تیر و ۳ تیر متوالی.',
    iconName: 'crosshair',
    killReward: 300,
    teamAccess: 'T'
  },
  usps: {
    id: 'usps',
    name: 'USP-S Tactical',
    persianName: 'یو‌اس‌پی تاکتیکال USP-S',
    slot: 2,
    category: 'pistol',
    price: 200,
    damageBody: 34,
    damageHead: 120,
    damageArmLeg: 26,
    clipSize: 12,
    maxReserveAmmo: 48,
    fireRateMs: 160,
    reloadTimeMs: 1800,
    recoilSpread: 0.015,
    recoilKickback: 0.020,
    range: 130,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    canHaveSilencer: true,
    description: 'کلت دقیق سازمانی ضدتروریست‌ها با صداخفه‌کن و دقت بالا در راندهای پیستول.',
    iconName: 'crosshair',
    killReward: 300,
    teamAccess: 'CT'
  },
  knife: {
    id: 'knife',
    name: 'Tactical Combat Knife',
    persianName: 'چاقوی تاکتیکال رزمی',
    slot: 3,
    category: 'melee',
    price: 0,
    damageBody: 35, // Left click slash
    damageHead: 65,
    damageArmLeg: 25,
    clipSize: 1,
    maxReserveAmmo: 1,
    fireRateMs: 400,
    reloadTimeMs: 0,
    recoilSpread: 0,
    recoilKickback: 0.01,
    range: 3.2,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'چاقوی نبرد نزدیک. ضربه از پشت (بک‌استپ) ۱۰۰ دمیج و مرگ فوری به همراه دارد. افزایش ۱۵٪ سرعت دویدن!',
    iconName: 'sword',
    killReward: 1500,
    teamAccess: 'all'
  },
  he_grenade: {
    id: 'he_grenade',
    name: 'High Explosive Grenade',
    persianName: 'نارنجک انفجاری HE Grenade',
    slot: 4,
    category: 'grenade',
    price: 300,
    damageBody: 80,
    damageHead: 80,
    damageArmLeg: 50,
    clipSize: 1,
    maxReserveAmmo: 1,
    fireRateMs: 1000,
    reloadTimeMs: 0,
    recoilSpread: 0,
    recoilKickback: 0.02,
    range: 40,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'نارنجک صوتی-انفجاری قوی با موج انفجار، لرزش دوربین و پخش ترکش تا شعاع ۸ متری.',
    iconName: 'bomb',
    killReward: 300,
    teamAccess: 'all'
  },
  flashbang: {
    id: 'flashbang',
    name: 'Flashbang Grenade',
    persianName: 'نارنجک کورکننده Flashbang',
    slot: 4,
    category: 'grenade',
    price: 200,
    damageBody: 0,
    damageHead: 0,
    damageArmLeg: 0,
    clipSize: 1,
    maxReserveAmmo: 2,
    fireRateMs: 1000,
    reloadTimeMs: 0,
    recoilSpread: 0,
    recoilKickback: 0.02,
    range: 40,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'نارنجک نوری که در صورت انفجار در زاویه دید، چشم بازیکنان و بات‌ها را سفید و صدای سوت گوش ایجاد می‌کند.',
    iconName: 'sun',
    killReward: 0,
    teamAccess: 'all'
  },
  smoke: {
    id: 'smoke',
    name: 'Smoke Grenade',
    persianName: 'نارنجک دودزا Smoke Grenade',
    slot: 4,
    category: 'grenade',
    price: 300,
    damageBody: 0,
    damageHead: 0,
    damageArmLeg: 0,
    clipSize: 1,
    maxReserveAmmo: 1,
    fireRateMs: 1000,
    reloadTimeMs: 0,
    recoilSpread: 0,
    recoilKickback: 0.02,
    range: 40,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'ایجاد توده متراکم دود خاکستری برای ۱۸ ثانیه جهت مسدود کردن دید اسنایپرها و دید بات‌ها.',
    iconName: 'cloud',
    killReward: 0,
    teamAccess: 'all'
  },
  c4: {
    id: 'c4',
    name: 'C4 Explosive Bomb',
    persianName: 'بمب انفجاری C4 (سی‌فور)',
    slot: 5,
    category: 'equipment',
    price: 0,
    damageBody: 500,
    damageHead: 500,
    damageArmLeg: 500,
    clipSize: 1,
    maxReserveAmmo: 0,
    fireRateMs: 3000,
    reloadTimeMs: 0,
    recoilSpread: 0,
    recoilKickback: 0,
    range: 5,
    availableFireModes: ['semi'],
    defaultFireMode: 'semi',
    description: 'بمب انفجاری C4 مخصوص تروریست‌ها. در بمب‌سایت A یا B کلید E یا شلیک را نگه‌دارید تا بمب کاشته شود (شمارشگر معکوس ۴۵ ثانیه‌ای تا انفجار اتمی).',
    iconName: 'bomb',
    killReward: 3500,
    teamAccess: 'T'
  }
};

export interface EquipmentItem {
  id: 'kevlar' | 'kevlar_helmet' | 'defuse_kit' | 'triple_weapon_perk';
  name: string;
  persianName: string;
  price: number;
  armorValue: number;
  hasHelmet: boolean;
  description: string;
  iconName: string;
  teamAccess: 'all' | 'T' | 'CT';
}

export const EQUIPMENT_REGISTRY: Record<string, EquipmentItem> = {
  kevlar: {
    id: 'kevlar',
    name: 'Kevlar Vest',
    persianName: 'جلیقه ضد گلوله (Kevlar)',
    price: 650,
    armorValue: 100,
    hasHelmet: false,
    description: 'کاهش ۵۰٪ صدمات وارد شده به سینه و تنه در برابر گلوله‌ها و ترکش نارنجک.',
    iconName: 'shield',
    teamAccess: 'all'
  },
  kevlar_helmet: {
    id: 'kevlar_helmet',
    name: 'Kevlar + Tactical Helmet',
    persianName: 'جلیقه + کلاهخود تاکتیکال',
    price: 1000,
    armorValue: 100,
    hasHelmet: true,
    description: 'حفاظت کامل از سر و بدن. جلوگیری از کشته شدن با تک‌تیر هدشات سلاح‌های ضعیف‌تر.',
    iconName: 'shield-check',
    teamAccess: 'all'
  },
  defuse_kit: {
    id: 'defuse_kit',
    name: 'Defuse Kit',
    persianName: 'کیت خنثی‌سازی بمب (Defuse Kit)',
    price: 400,
    armorValue: 0,
    hasHelmet: false,
    description: 'کاهش زمان خنثی‌سازی بمب C4 از ۱۰ ثانیه به ۵ ثانیه.',
    iconName: 'tool',
    teamAccess: 'CT'
  },
  triple_weapon_perk: {
    id: 'triple_weapon_perk',
    name: 'Tactical 3-Weapon Sling',
    persianName: 'بند حمایل تاکتیکال (حمل ۳ اسلحه همزمان)',
    price: 5000,
    armorValue: 0,
    hasHelmet: false,
    description: 'قابلیت ویژه حمل ۳ سلاح گرم به صورت همزمان (مثلاً AWP + کلاشینکف AK-47 + دسرتیگل یا هر ترکیب دلخواه)! باز شدن اسلات ۶ با کلید [6].',
    iconName: 'backpack',
    teamAccess: 'all'
  }
};
